# Generated by Django 6.0.3 on 2026-03-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_submission_year_produced_submission_consent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TShirtOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("shipping_address", models.TextField()),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        default="M",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("dark_grey", "Dark Grey"), ("black", "Black")],
                        default="dark_grey",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("amount", models.PositiveIntegerField(help_text="Amount in GBP")),
                ("paid", models.BooleanField(default=False)),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
