# Generated by Django 6.0.3 on 2026-03-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_tshirtorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tshirtorder",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                    ("XXXL", "Triple Extra Large"),
                ],
                default="M",
                max_length=10,
            ),
        ),
    ]
