# Generated by Django 6.0.3 on 2026-03-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tshirtorder_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirtorder',
            name='shipping_address',
        ),
    ]
