# Generated by Django 6.0.3 on 2026-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_tshirtorder_shipping_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="genre",
            field=models.CharField(
                choices=[
                    ("narrative", "Narrative"),
                    ("documentary", "Documentary"),
                    ("experimental", "Experimental"),
                    ("animation", "Animation"),
                ],
                max_length=50,
            ),
        ),
    ]
