# Generated by Django 6.0.3 on 2026-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_submission_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="duration",
        ),
        migrations.AlterField(
            model_name="submission",
            name="genre",
            field=models.CharField(max_length=50),
        ),
    ]
